/*
SQLyog Ultimate
MySQL - 10.1.36-MariaDB : Database - db_mandala_sari
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `anggota` */

DROP TABLE IF EXISTS `anggota`;

CREATE TABLE `anggota` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) DEFAULT NULL,
  `jabatan` varchar(255) DEFAULT NULL,
  `no_hp` varchar(255) DEFAULT NULL,
  `pendidikan` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;

/*Data for the table `anggota` */

insert  into `anggota`(`id`,`nama`,`jabatan`,`no_hp`,`pendidikan`) values 
(1,'I Made Suarjana','Penasehat Kepala Desa','03617811146','S1'),
(2,'I Gusti Agung Gde Putra','Pengawas Ketua',NULL,'S1'),
(3,'I Wayan Darsana','Pengawas Anggota',NULL,'SMP'),
(4,'Ida Bagus Gede Manu Drestha','Pengelola Ketua','0811397302','S1'),
(5,'I Putu Adi Satyawan','Pengelola Wakil Ketua','081239465624','S1'),
(6,'I Wayan Suweja','Pengelola Sekretaris','08123616157','SMP'),
(7,'I Made Mustika Yasa','Pengelola Bendahara','','S1'),
(8,'I Ketut Lastra','Pengelola Kepala Unit Usaha Air','081239005763','SMA'),
(9,'I Nyoman Sukena ','Pengelola Kepala Unit Usaha Perdagangan dan Jasa','085237839336','SMA'),
(10,'I Wayan Mahardika','Pengelola Kepala Unit Usaha Wisata','08123640761','SMA'),
(11,'I Ketut Sucitra','Pegawai Usaha Jasa Angkut Sampah',NULL,'SMA'),
(12,'I Nyoman Baktiana','Pegawai Usaha Jasa Angkut Sampah',NULL,'SD'),
(13,'I Made Suwanta','Pegawai Usaha Jasa Angkut Sampah','085237101514','SMA'),
(14,'Ni Wayan Indah','Pegawai Usaha Toko','08760890735','SMA');

/*Table structure for table `blog` */

DROP TABLE IF EXISTS `blog`;

CREATE TABLE `blog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `judul` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `id_kategori` int(11) DEFAULT NULL,
  `id_penulis` int(11) DEFAULT NULL,
  `isi` text,
  `gambar` varchar(255) DEFAULT 'default.jpg',
  `dikunjungi` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=latin1;

/*Data for the table `blog` */

insert  into `blog`(`id`,`judul`,`url`,`id_kategori`,`id_penulis`,`isi`,`gambar`,`dikunjungi`,`created_at`,`updated_at`) values 
(1,'Blog Olah Raga No. 1','blog-olah-raga-no-1',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',1006,'2018-11-20 00:00:00','2020-04-23 11:00:20'),
(2,'Blog Olah Raga No. 2','blog-olah-raga-no-2',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',172,'2019-10-21 00:00:00','2020-04-23 11:00:20'),
(3,'Blog Kesehatan No. 3','blog-kesehatan-no-3',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',562,'2018-07-28 00:00:00','2020-04-23 11:00:20'),
(4,'Blog Kuliner No. 4','blog-kuliner-no-4',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',266,'2019-12-14 00:00:00','2020-04-23 11:00:20'),
(5,'Blog Olah Raga No. 5','blog-olah-raga-no-5',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',65,'2019-07-19 00:00:00','2020-04-23 11:00:20'),
(6,'Blog Kuliner No. 6','blog-kuliner-no-6',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',394,'2019-09-15 00:00:00','2020-04-23 11:00:20'),
(7,'Blog Kuliner No. 7','blog-kuliner-no-7',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',59,'2019-03-14 00:00:00','2020-04-23 11:00:20'),
(8,'Blog Kesehatan No. 8','blog-kesehatan-no-8',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',673,'2018-01-20 00:00:00','2020-04-23 11:00:20'),
(9,'Blog Olah Raga No. 9','blog-olah-raga-no-9',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',40,'2019-01-09 00:00:00','2020-04-23 11:00:20'),
(10,'Blog Hiburan No. 10','blog-hiburan-no-10',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',587,'2019-11-14 00:00:00','2020-04-23 11:00:20'),
(11,'Blog Hiburan No. 11','blog-hiburan-no-11',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',171,'2019-01-11 00:00:00','2020-04-23 11:00:20'),
(12,'Blog Hiburan No. 12','blog-hiburan-no-12',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',153,'2018-10-08 00:00:00','2020-04-23 11:00:20'),
(13,'Blog Kuliner No. 13','blog-kuliner-no-13',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',434,'2019-03-24 00:00:00','2020-04-23 11:00:20'),
(14,'Blog Hiburan No. 14','blog-hiburan-no-14',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',630,'2019-01-16 00:00:00','2020-04-23 11:00:20'),
(15,'Blog Hiburan No. 15','blog-hiburan-no-15',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',609,'2018-05-24 00:00:00','2020-04-23 11:00:20'),
(16,'Blog Hiburan No. 16','blog-hiburan-no-16',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',612,'2018-08-19 00:00:00','2020-04-23 11:00:20'),
(17,'Blog Kesehatan No. 17','blog-kesehatan-no-17',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',943,'2019-01-12 00:00:00','2020-04-23 11:00:21'),
(18,'Blog Kesehatan No. 18','blog-kesehatan-no-18',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',962,'2018-09-13 00:00:00','2020-04-23 11:00:21'),
(19,'Blog Kesehatan No. 19','blog-kesehatan-no-19',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',611,'2019-10-07 00:00:00','2020-04-23 11:00:21'),
(20,'Blog Hiburan No. 20','blog-hiburan-no-20',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',547,'2019-03-20 00:00:00','2020-04-23 11:00:21'),
(21,'Blog Kuliner No. 21','blog-kuliner-no-21',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',177,'2019-09-25 00:00:00','2020-04-23 11:00:21'),
(22,'Blog Olah Raga No. 22','blog-olah-raga-no-22',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',262,'2018-12-22 00:00:00','2020-04-23 11:00:21'),
(23,'Blog Kuliner No. 23','blog-kuliner-no-23',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',167,'2018-03-23 00:00:00','2020-04-23 11:00:21'),
(24,'Blog Kesehatan No. 24','blog-kesehatan-no-24',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',769,'2019-02-04 00:00:00','2020-04-23 11:00:21'),
(25,'Blog Kesehatan No. 25','blog-kesehatan-no-25',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',854,'2018-10-24 00:00:00','2020-04-23 11:00:21'),
(26,'Blog Hiburan No. 26','blog-hiburan-no-26',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',577,'2019-03-06 00:00:00','2020-04-23 11:00:21'),
(27,'Blog Hiburan No. 27','blog-hiburan-no-27',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',100,'2018-07-23 00:00:00','2020-04-23 11:00:21'),
(28,'Blog Hiburan No. 28','blog-hiburan-no-28',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',634,'2018-12-10 00:00:00','2020-04-23 11:00:21'),
(29,'Blog Hiburan No. 29','blog-hiburan-no-29',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',981,'2018-10-04 00:00:00','2020-04-23 11:00:21'),
(30,'Blog Kesehatan No. 30','blog-kesehatan-no-30',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',530,'2019-06-17 00:00:00','2020-04-23 11:00:21'),
(31,'Blog Kuliner No. 31','blog-kuliner-no-31',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',294,'2019-11-04 00:00:00','2020-04-23 11:00:21'),
(32,'Blog Olah Raga No. 32','blog-olah-raga-no-32',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',554,'2019-05-22 00:00:00','2020-04-23 11:00:21'),
(33,'Blog Hiburan No. 33','blog-hiburan-no-33',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',249,'2018-01-01 00:00:00','2020-04-23 11:00:21'),
(34,'Blog Hiburan No. 34','blog-hiburan-no-34',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',948,'2019-04-07 00:00:00','2020-04-23 11:00:21'),
(35,'Blog Kuliner No. 35','blog-kuliner-no-35',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',855,'2019-04-15 00:00:00','2020-04-23 11:00:21'),
(36,'Blog Kuliner No. 36','blog-kuliner-no-36',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',5,'2018-09-20 00:00:00','2020-04-23 11:00:21'),
(37,'Blog Kesehatan No. 37','blog-kesehatan-no-37',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',296,'2019-12-21 00:00:00','2020-04-23 11:00:21'),
(38,'Blog Hiburan No. 38','blog-hiburan-no-38',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',321,'2019-09-01 00:00:00','2020-04-23 11:00:21'),
(39,'Blog Olah Raga No. 39','blog-olah-raga-no-39',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',461,'2019-10-17 00:00:00','2020-04-23 11:00:22'),
(40,'Blog Kesehatan No. 40','blog-kesehatan-no-40',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',332,'2019-09-25 00:00:00','2020-04-23 11:00:22'),
(41,'Blog Kesehatan No. 41','blog-kesehatan-no-41',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',414,'2019-02-11 00:00:00','2020-04-23 11:00:22'),
(42,'Blog Olah Raga No. 42','blog-olah-raga-no-42',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',145,'2019-08-16 00:00:00','2020-04-23 11:00:22'),
(43,'Blog Kesehatan No. 43','blog-kesehatan-no-43',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',903,'2018-01-07 00:00:00','2020-04-23 11:00:22'),
(44,'Blog Kesehatan No. 44','blog-kesehatan-no-44',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',96,'2018-03-27 00:00:00','2020-04-23 11:00:22'),
(45,'Blog Kuliner No. 45','blog-kuliner-no-45',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',754,'2019-09-05 00:00:00','2020-04-23 11:00:22'),
(46,'Blog Olah Raga No. 46','blog-olah-raga-no-46',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',991,'2019-09-20 00:00:00','2020-04-23 11:00:22'),
(47,'Blog Kuliner No. 47','blog-kuliner-no-47',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',284,'2018-08-06 00:00:00','2020-04-23 11:00:22'),
(48,'Blog Kuliner No. 48','blog-kuliner-no-48',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',422,'2018-04-23 00:00:00','2020-04-23 11:00:22'),
(49,'Blog Hiburan No. 49','blog-hiburan-no-49',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',950,'2018-02-21 00:00:00','2020-04-23 11:00:22'),
(50,'Blog Hiburan No. 50','blog-hiburan-no-50',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',314,'2018-04-04 00:00:00','2020-04-23 11:00:22'),
(51,'Blog Kuliner No. 51','blog-kuliner-no-51',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',871,'2018-04-02 00:00:00','2020-04-23 11:00:22'),
(52,'Blog Kesehatan No. 52','blog-kesehatan-no-52',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',219,'2018-03-03 00:00:00','2020-04-23 11:00:22'),
(53,'Blog Kuliner No. 53','blog-kuliner-no-53',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',899,'2018-09-13 00:00:00','2020-04-23 11:00:22'),
(54,'Blog Hiburan No. 54','blog-hiburan-no-54',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',929,'2018-02-23 00:00:00','2020-04-23 11:00:22'),
(55,'Blog Kuliner No. 55','blog-kuliner-no-55',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',86,'2018-07-09 00:00:00','2020-04-23 11:00:22'),
(56,'Blog Hiburan No. 56','blog-hiburan-no-56',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',221,'2019-12-08 00:00:00','2020-04-23 11:00:22'),
(57,'Blog Olah Raga No. 57','blog-olah-raga-no-57',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',506,'2018-07-11 00:00:00','2020-04-23 11:00:22'),
(58,'Blog Hiburan No. 58','blog-hiburan-no-58',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',833,'2018-04-19 00:00:00','2020-04-23 11:00:22'),
(59,'Blog Kuliner No. 59','blog-kuliner-no-59',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',930,'2019-11-19 00:00:00','2020-04-23 11:00:22'),
(60,'Blog Olah Raga No. 60','blog-olah-raga-no-60',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',128,'2018-10-05 00:00:00','2020-04-23 11:00:22'),
(61,'Blog Kuliner No. 61','blog-kuliner-no-61',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',820,'2019-05-06 00:00:00','2020-04-23 11:00:22'),
(62,'Blog Olah Raga No. 62','blog-olah-raga-no-62',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',154,'2018-10-15 00:00:00','2020-04-23 11:00:22'),
(63,'Blog Kuliner No. 63','blog-kuliner-no-63',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',26,'2019-11-20 00:00:00','2020-04-23 11:00:23'),
(64,'Blog Olah Raga No. 64','blog-olah-raga-no-64',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',513,'2018-07-16 00:00:00','2020-04-23 11:00:23'),
(65,'Blog Kuliner No. 65','blog-kuliner-no-65',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',279,'2019-11-02 00:00:00','2020-04-23 11:00:23'),
(66,'Blog Kesehatan No. 66','blog-kesehatan-no-66',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',398,'2019-11-26 00:00:00','2020-04-23 11:00:23'),
(67,'Blog Kuliner No. 67','blog-kuliner-no-67',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',293,'2018-04-22 00:00:00','2020-04-23 11:00:23'),
(68,'Blog Kuliner No. 68','blog-kuliner-no-68',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',730,'2018-03-16 00:00:00','2020-04-23 11:00:23'),
(69,'Blog Olah Raga No. 69','blog-olah-raga-no-69',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',961,'2019-03-21 00:00:00','2020-04-23 11:00:23'),
(70,'Blog Kuliner No. 70','blog-kuliner-no-70',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',396,'2019-05-16 00:00:00','2020-04-23 11:00:23'),
(71,'Blog Kuliner No. 71','blog-kuliner-no-71',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',526,'2018-11-06 00:00:00','2020-04-23 11:00:23'),
(72,'Blog Olah Raga No. 72','blog-olah-raga-no-72',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',625,'2019-11-16 00:00:00','2020-04-23 11:00:23'),
(73,'Blog Hiburan No. 73','blog-hiburan-no-73',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',89,'2018-02-19 00:00:00','2020-04-23 11:00:23'),
(74,'Blog Kesehatan No. 74','blog-kesehatan-no-74',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',881,'2018-07-23 00:00:00','2020-04-23 11:00:23'),
(75,'Blog Hiburan No. 75','blog-hiburan-no-75',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',185,'2018-10-12 00:00:00','2020-04-23 11:00:23'),
(76,'Blog Kuliner No. 76','blog-kuliner-no-76',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',795,'2018-09-18 00:00:00','2020-04-23 11:00:24'),
(77,'Blog Kesehatan No. 77','blog-kesehatan-no-77',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',40,'2018-06-23 00:00:00','2020-04-23 11:00:24'),
(78,'Blog Hiburan No. 78','blog-hiburan-no-78',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',197,'2018-10-18 00:00:00','2020-04-23 11:00:24'),
(79,'Blog Kuliner No. 79','blog-kuliner-no-79',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',182,'2019-01-28 00:00:00','2020-04-23 11:00:24'),
(80,'Blog Hiburan No. 80','blog-hiburan-no-80',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',871,'2018-06-06 00:00:00','2020-04-23 11:00:24'),
(81,'Blog Olah Raga No. 81','blog-olah-raga-no-81',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',607,'2019-06-28 00:00:00','2020-04-23 11:00:24'),
(82,'Blog Kesehatan No. 82','blog-kesehatan-no-82',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',490,'2019-08-23 00:00:00','2020-04-23 11:00:24'),
(83,'Blog Hiburan No. 83','blog-hiburan-no-83',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',915,'2018-06-09 00:00:00','2020-04-23 11:00:24'),
(84,'Blog Kuliner No. 84','blog-kuliner-no-84',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',425,'2018-12-06 00:00:00','2020-04-23 11:00:24'),
(85,'Blog Kuliner No. 85','blog-kuliner-no-85',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',809,'2018-08-17 00:00:00','2020-04-23 11:00:24'),
(86,'Blog Kesehatan No. 86','blog-kesehatan-no-86',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',529,'2018-03-28 00:00:00','2020-04-23 11:00:24'),
(87,'Blog Kesehatan No. 87','blog-kesehatan-no-87',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',595,'2019-02-01 00:00:00','2020-04-23 11:00:24'),
(88,'Blog Olah Raga No. 88','blog-olah-raga-no-88',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',662,'2019-07-01 00:00:00','2020-04-23 11:00:24'),
(89,'Blog Hiburan No. 89','blog-hiburan-no-89',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',374,'2019-09-24 00:00:00','2020-04-23 11:00:24'),
(90,'Blog Kuliner No. 90','blog-kuliner-no-90',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',815,'2019-03-15 00:00:00','2020-04-23 11:00:24'),
(91,'Blog Kuliner No. 91','blog-kuliner-no-91',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',414,'2018-08-17 00:00:00','2020-04-23 11:00:24'),
(92,'Blog Hiburan No. 92','blog-hiburan-no-92',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',194,'2019-09-12 00:00:00','2020-04-23 11:00:24'),
(93,'Blog Kesehatan No. 93','blog-kesehatan-no-93',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',155,'2019-06-08 00:00:00','2020-04-23 11:00:25'),
(94,'Blog Hiburan No. 94','blog-hiburan-no-94',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',876,'2019-10-21 00:00:00','2020-04-23 11:00:25'),
(95,'Blog Hiburan No. 95','blog-hiburan-no-95',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',381,'2019-12-04 00:00:00','2020-04-23 11:00:25'),
(96,'Blog Olah Raga No. 96','blog-olah-raga-no-96',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',761,'2018-09-04 00:00:00','2020-04-23 11:00:25'),
(97,'Blog Hiburan No. 97','blog-hiburan-no-97',5,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','hiburan.jpg',370,'2018-08-23 00:00:00','2020-04-23 11:00:25'),
(98,'Blog Kuliner No. 98','blog-kuliner-no-98',3,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kuliner.jpg',868,'2018-07-23 00:00:00','2020-04-23 11:00:25'),
(99,'Blog Olah Raga No. 99','blog-olah-raga-no-99',4,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','olahraga.jpg',359,'2019-03-20 00:00:00','2020-04-23 11:00:25'),
(100,'Blog Kesehatan No. 100','blog-kesehatan-no-100',1,1,'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\n							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\n							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\n							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\n							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','kesehatan.jpg',471,'2019-04-18 00:00:00','2020-04-23 11:00:25');

/*Table structure for table `informasi` */

DROP TABLE IF EXISTS `informasi`;

CREATE TABLE `informasi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) DEFAULT NULL,
  `no_telepon` varchar(255) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `alamat` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `informasi` */

insert  into `informasi`(`id`,`email`,`no_telepon`,`facebook`,`twitter`,`alamat`) values 
(1,'mandalasari2019@gmail.com ','(+62) 81-236-236-221',NULL,NULL,NULL);

/*Table structure for table `jenis_unit_usaha` */

DROP TABLE IF EXISTS `jenis_unit_usaha`;

CREATE TABLE `jenis_unit_usaha` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

/*Data for the table `jenis_unit_usaha` */

insert  into `jenis_unit_usaha`(`id`,`nama`,`created_at`,`updated_at`) values 
(1,'Unit Usaha Wisata','2020-04-16 18:26:10','2020-04-16 17:24:20'),
(2,'Unit Usaha Air','2020-04-16 18:27:34','2020-04-16 18:27:36'),
(3,'Unit Usaha Perdagangan dan jasa','2020-04-16 18:28:07','2020-04-19 15:42:27'),
(6,'Unit Usaha Kuliner','2020-04-19 14:16:42','2020-04-19 14:16:42');

/*Table structure for table `jenis_user` */

DROP TABLE IF EXISTS `jenis_user`;

CREATE TABLE `jenis_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `jenis_user` */

insert  into `jenis_user`(`id`,`nama`) values 
(1,'Administrator');

/*Table structure for table `kategori_blog` */

DROP TABLE IF EXISTS `kategori_blog`;

CREATE TABLE `kategori_blog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Data for the table `kategori_blog` */

insert  into `kategori_blog`(`id`,`nama`,`created_at`,`updated_at`) values 
(1,'Kesehatan','2020-04-17 17:32:39','2020-04-17 17:32:39'),
(3,'Kuliner','2020-04-17 17:39:08','2020-04-17 17:39:08'),
(4,'Olah Raga','2020-04-17 17:39:21','2020-04-17 17:39:21'),
(5,'Hiburan','2020-04-17 17:39:30','2020-04-17 17:39:30');

/*Table structure for table `unit_usaha` */

DROP TABLE IF EXISTS `unit_usaha`;

CREATE TABLE `unit_usaha` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_jenis` int(11) DEFAULT NULL,
  `nama` varchar(255) NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  `gambar` varchar(255) DEFAULT 'default.jpg',
  `deskripsi` text,
  `dikunjungi` int(11) DEFAULT '0',
  `id_penulis` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

/*Data for the table `unit_usaha` */

insert  into `unit_usaha`(`id`,`id_jenis`,`nama`,`url`,`gambar`,`deskripsi`,`dikunjungi`,`id_penulis`,`created_at`,`updated_at`) values 
(1,1,'Mandala Sari Cycling','mandala-sari-cycling','5e9bfe41bd240.jpg','<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga animi dolor, fugit, quidem maxime expedita amet molestiae! Neque doloremque consequuntur, voluptatibus ipsam deserunt vel est minima ullam possimus consectetur unde.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga animi dolor, fugit, quidem maxime expedita amet molestiae! Neque doloremque consequuntur, voluptatibus ipsam deserunt vel est minima ullam possimus consectetur unde.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga animi dolor, fugit, quidem maxime expedita amet molestiae! Neque doloremque consequuntur, voluptatibus ipsam deserunt vel est minima ullam possimus consectetur unde.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga animi dolor, fugit, quidem maxime expedita amet molestiae! Neque doloremque consequuntur, voluptatibus ipsam deserunt vel est minima ullam possimus consectetur unde.</p><p><br></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga animi dolor, fugit, quidem maxime expedita amet molestiae! Neque doloremque consequuntur, voluptatibus ipsam deserunt vel est minima ullam possimus consectetur unde.</p><p>                                            \r\n                                        </p>',22,1,'2020-04-17 22:31:31','2020-04-19 07:31:19'),
(2,1,'Mandala Sari Rafting','mandala-sari-rafting','5e9bfde377f8e.jpg',NULL,5,1,'2020-04-17 22:31:33','2020-04-19 07:29:42'),
(3,1,'Penyewaan Boat Rafting','penyewaan-boat-rafting','5e9c04a3db1e4.jpg',NULL,5,1,'2020-04-17 22:31:35','2020-04-23 10:34:00'),
(4,2,'PAM Desa','pam-desa','5e9bfd45451eb.jpg',NULL,6,1,'2020-04-17 22:31:36','2020-04-19 07:27:07'),
(5,2,'Air Galon Toya Langon','air-galon-toya-langon','5e9c06ac8c24e.jpg',NULL,2,1,'2020-04-17 22:31:38','2020-04-19 08:07:08'),
(6,3,'Jasa Angkut Sampah','jasa-angkut-sampah','5e9c063b39f07.jpg',NULL,2,1,'2020-04-17 22:31:40','2020-04-19 08:05:20'),
(7,3,'Mandala Sari Mart','mandala-sari-mart','5e9c06f0b8e6d.jpg',NULL,3,1,'2020-04-17 22:31:43','2020-04-19 08:08:22'),
(16,6,'Warung Sawah Sawah','warung-sawah-sawah','5e9c5dbd9481d.jpg',NULL,2,1,'2020-04-19 14:17:18','2020-04-19 15:34:09');

/*Table structure for table `user` */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_jenis` int(11) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `foto_profil` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `remember_token` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `user` */

insert  into `user`(`id`,`id_jenis`,`username`,`nama`,`foto_profil`,`password`,`remember_token`,`created_at`,`updated_at`) values 
(1,1,'admin','I Wayan Gus Arisna','default.png','$2y$12$wYOanWRmUfCbSChV/BHiM.WApA7hHXvnUFogc3CWntommM2Mv66tW',NULL,'2020-04-16 18:58:40','2020-04-16 18:58:42');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
